# Goal definition (sent from client to server)
int32 drone_id                # ID of the drone
string action                 # The action to perform 
string mission                # The mission to perform 

# Action-specific parameters
float64 takeoff_height       

float64 latitude              
float64 longitude             
float64 altitude              

float64 x                    
float64 y                    
float64 z                
float64 yaw

float64 hover_time            

string emergency_type        

Waypoint[] waypoints          # List of waypoints for a waypoint mission

float64 radius                
float64 angular_speed        
float64 number_of_cycles      

---
# Result definition (sent from server to client when the action completes)
bool success                  # Whether the action was successful
string message                # Message detailing the result

---
# Feedback definition (sent from server to client during action execution)
float64 err_latitude      # Error latitude between real and sim drone
float64 err_longitude     # Error longitude between real and sim drone
float64 err_altitude      # Error altitude between real and sim drone
float64 err_yaw
