int32 drone_id
int32 flight_status
int32 error_status
int32 gear
int32 mode

geometry_msgs/Point global_position
geometry_msgs/Point ext_position
int32 ext_position_status  
geometry_msgs/Twist velocity
float64 yaw
float64 q0
float64 q1
float64 q2
float64 q3
geometry_msgs/Twist rc_data

float64 avoid_down
float64 avoid_back
float64 avoid_right
float64 avoid_left
float64 avoid_front
float64 avoid_up

float64 battery_capacity
float64 battery_voltage
float64 battery_current
float64 battery_percentage

float64 timestamp

